language: node_js
node_js:
- stable
notifications:
  email:
    on_success: change
    on_failure: always
cache:
  directories:
  - node_modules
  - bower_components
env:
  global:
  - secure: TBTq6fxGLwsimS+KClPFjFltRfNiNcj01ztbPgtFARlNTPWkoq43av3rCuBZLAeudiFqFxqArVNiQ+hRnL8PDqQNldAdZEkB9jqcGQKHh+S9u3sU9mGLFvXkbIwLo3NWCSYs1S48SBMtr7LZkCU/0jxgNWk/Y4tPjs7lBxcq9aLIUJPcygv6UXrVWwlRcY3J0/2ttflaim59XIXUy2Oxmn7ulXPthIpjwbNoQE0jRkoZgwEWKnLLmUT0fdb2nR75jnqg9NklcThoYWpJeyM0f/uSMQJsvltK9nPQrMAybiNrwIWB8ijYJ8FWU91ebzek8JZhsXEQIaDiO3xTPPL/9OVUZGUiWunjfRIA+3WDTekgJyd52l+3VaIUMnz/+mDiKDqPh6ena9dpaRNcdGT72CPaewmcibGB+1iDJXjm4ph5ySNncI0zhDRMBD49hhrW9C+x2Y05qb13wGAdtoLIA9R1m/CZcXuC0LrUMK2KaWEhjFJKJ51mXi0BXYG4scVePmYp2Mrs6sjdhRnceIu7qxTfdvLq8g6WDhQrpV0LsKGHR3J40ThNqA2aLzOfuCwCBGeJ0qVknkAd4H7xRT9a3OuQUUOdzPZ5ltBxQLGxk10uO8DivaOcpgkt13zf3eVZeMGz9pTyGJk9v4vGyeq8wKb2x+ZW/Bz/xVrDcci9BfM= # AUTH_COOKIE
  - secure: 17aRxI91GoOSt81k459sWoKZp3/DrBuYXzcsPOLEu0ivc71v3eSULDl7eY6mOmavsKhx6v36jvx92Ry0MH1GeAfknXIDlQ3NWaS3F5X5g1t7bg6TmZzRFQ4MGt2N0uU8CAHrarbJfo+xvnsTadhVSqxttRcNYzv3GsArZuk0VbQo6cakKq/4GHnteGVW2AUQ9Laje11n7gbi5ZnQ2vEnXuIMZPNuydJOKWr7nfvsqjFnJ22kYWDF2U/e4baoODBk3iffanQW6oqnZQ/F+MmdlT4hQ+mcEAcYf63t6knhI4Cp46bSNsYqjxSoOR/NxVHBCNPr9TT/8YjX3H1wm03IQS4QNJj0NjWb75FSiAfzdDa9ELjihE6dmjBc8wPkrVMLCrErni4gw4BUi2oOk/mnTqa4GfSFaaGteFmpIcQNw/m5zhZaDkGd8Ne2RVgC7+iMm1aZFFuicMYle33wvRRIeQlZfrTUc5CJNi6c6ctAy24fmyxVywcuwMOdr0leOsx8Fxy6kkV9Cf8r2+4YVIJUb+ruIRPj+Edv2eGRa5gU7sLnYphMwZiyzbvldmNITzfk8R7bELfzGjqQcUnM0t1YELjWtMmpumjreULdjxRRT1oLxaB4XcKAaKkxgYTMsCZMQwJk6eLz7eNSIMXF4TEJaYFMD98YibJ/2CazGrzbbcU= # EMREST_URL
