language: node_js

node_js:
    - "stable"

notifications:
    email:
        on_success: change
        on_failure: always

cache:
    directories:
        - node_modules
        - bower_components

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start