site_name: ERMrestJS
site_description: The ermrestjs library is a client API for the ERMrest service. It provides a higher-level, simplified interface for working with the entity-relationship concepts that are native to ERMrest.
theme: readthedocs
site_url: https://informatics-isi-edu.github.io/ermrestjs/

copyright: Copyright &copy; 2018 <a href="<https://github.com/informatics-isi-edu/ermrestjs>">ermerstjs</a>.

pages:
    - Welcome to the documentation: index.md
    - User Documents:
        - AngularJS Usage: user-docs/angular.md
        - Facet JSON Structure: user-docs/facet-json.md
        - Facet Examples: user-docs/facet-examples.md
        - Handlebars Usage: user-docs/handlebars.md
        - Preformat Annotation: user-docs/pre-format.md
        - Pseudo Columns: user-docs/pseudo-columns.md
        - Table Alternatives: user-docs/table-alternatives.md
        - Template And Markdown Guide: user-docs/template-markdown.md
    - Developer Documents:
        - API Reference: dev-docs/api.md
        - Test Idioms: dev-docs/test-idoms.md
        - Unit Testing: dev-docs/unit-test.md
